# Introducción

*   Introducción a google Colab
*   Introduccion a pandas

In [1]:
print("Hola Mundo")

Hola Mundo

In [6]:
a = 'a'
print(a)
print(type(a))

a
<class 'str'>

In [7]:
a = [1,'2']
print(a)
print(type(a))

[1, '2']
<class 'list'>

In [8]:
a = {1:'2'}
print(a)
print(type(a))

{1: '2'}
<class 'dict'>

In [9]:
a = 1
print(a)
print(type(a))

1
<class 'int'>

In [10]:
a = 1.2
print(a)
print(type(a))

1.2
<class 'float'>

In [11]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [15]:
a=1
while a==1:
  print(a)
  a= a+1

1

In [19]:
a

2

In [18]:

if a==3:
    print('Verdadero')
else:
    print('Falso')

Falso

# Pandas

Librería de python enfocada en la manipulación de datos

* Series
* DataFrames

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statistics as stats
import math as m
import sklearn as sk

In [3]:
df = pd.read_excel('https://github.com/Baeltor/PCD/raw/main/Datos/BO_HeartData.xlsx', engine='openpyxl')

In [4]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.shape

(303, 15)

### Lectura de archivo "desde" local

In [6]:
df_estudiantes = pd.read_excel('Estudiantes.xlsx', engine='openpyxl')

/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [12]:
df_estudiantes

,Nombre,Apellido(s),Número de ID,Dirección de correo,Grupos
0,YESSICA,ACUÑA BARRANTES,1.018485e+09,yessica-acuna@upc.edu.co,NaN
1,SIRLY HASLEIDY,AGUDELO QUINTERO,1.014224e+09,sagudelo18@upc.edu.co,NaN
2,FERNANDO,AGUILAR GARCIA,1.738965e+07,fernando-aguilar@upc.edu.co,NaN
3,KIARA INES,ARCHBOLD ANGARITA,1.018483e+09,kiara-archold@upc.edu.co,NaN
4,ANA MARIA,AREVALO AMAYA,1.123086e+09,ana-arevalo3@upc.edu.co,NaN
...,...,...,...,...,...
153,EDDY PAULINE,VASQUEZ RODRIGUEZ,1.022373e+09,eddy-vasquez@upc.edu.co,NaN
154,OSCAR LEONARDO,VEGA CASTRO,1.075661e+09,oscar-vega2@upc.edu.co,NaN
155,FREDDY EDUARDO,VILLAFAÑE FUENTES,1.046873e+09,freddy-villafane@upc.edu.co,NaN
156,Nohemi,Villarreal Navarro,1.022392e+09,nohemi-villarreal@upc.edu.co,NaN
157,KAREN JULIETH,ZABALA CASTAÑEDA,1.032487e+09,karen-zabala@upc.edu.co,NaN

In [16]:
df_estudiantes.columns

Index(['Nombres', 'Apellidos', 'Id', 'Email', 'Grupo'], dtype='object')

In [15]:
df_estudiantes.rename(columns={'Nombre':'Nombres',
                               'Apellido(s)': 'Apellidos',
                               'Número de ID': 'Id',
                               'Dirección de correo': 'Email',
                               'Grupos': 'Grupo'}, inplace=True)

In [21]:
df_estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Nombres    158 non-null    object
 1   Apellidos  158 non-null    object
 2   Id         158 non-null    object
 3   Email      158 non-null    object
 4   Grupo      0 non-null      float64
dtypes: float64(1), object(4)
memory usage: 6.3+ KB

In [20]:
df_estudiantes.Id = df_estudiantes.Id.astype(str)

In [45]:
df_estudiantes # shift + enter

,Nombres,Apellidos,Id,Email,Grupo
0,YESSICA,ACUÑA BARRANTES,1018485174,yessica-acuna@upc.edu.co,NaN
1,SIRLY HASLEIDY,AGUDELO QUINTERO,1014224233,sagudelo18@upc.edu.co,NaN
2,FERNANDO,AGUILAR GARCIA,17389648,fernando-aguilar@upc.edu.co,NaN
3,KIARA INES,ARCHBOLD ANGARITA,1018482816,kiara-archold@upc.edu.co,NaN
4,ANA MARIA,AREVALO AMAYA,1123086225,ana-arevalo3@upc.edu.co,NaN
...,...,...,...,...,...
153,EDDY PAULINE,VASQUEZ RODRIGUEZ,1022372740,eddy-vasquez@upc.edu.co,NaN
154,OSCAR LEONARDO,VEGA CASTRO,1075661411,oscar-vega2@upc.edu.co,NaN
155,FREDDY EDUARDO,VILLAFAÑE FUENTES,1046873078,freddy-villafane@upc.edu.co,NaN
156,NOHEMI,VILLARREAL NAVARRO,1022391981,nohemi-villarreal@upc.edu.co,NaN
157,KAREN JULIETH,ZABALA CASTAÑEDA,1032487033,karen-zabala@upc.edu.co,NaN

In [43]:
def mayus_to_minus(string):
    # Convierte una cadena a minúsculas
    string = string.lower()
    return string

def minus_to_mayus(string):
    # Convierte una cadena a mayúsculas
    string = string.upper()
    return string

In [34]:
df_estudiantes.Nombres = df_estudiantes.Nombres.apply(minus_to_mayus)
df_estudiantes.Apellidos = df_estudiantes.Apellidos.apply(minus_to_mayus)

In [36]:
# (1018485174.0) Funciíon para quitar el .0 de los documentos

def quitar_ceros(string):
    string = string.replace('.0','')
    return string

In [38]:
quitar_ceros('1018485174.0')

'1018485174'

In [40]:
df_estudiantes['Id'] = df_estudiantes['Id'].apply(quitar_ceros)

In [47]:
# prompt: crea una función que asigne de forma aleatoria a los estudiantes en grupos de máximo 6 personas, con un máximo de 27 grupos y que el grupo quede en la variable Grupo

import pandas as pd
import numpy as np
def asignar_grupos_aleatorios(df):
    """
    Asigna aleatoriamente a los estudiantes en grupos de máximo 6 personas,
    con un máximo de 27 grupos.

    Args:
        df (pd.DataFrame): DataFrame con una columna 'Grupo'.

    Returns:
        pd.DataFrame: DataFrame con la columna 'Grupo' actualizada.
    """
    # Número de estudiantes
    num_estudiantes = len(df)

    # Calcular el número mínimo de grupos necesarios
    min_grupos = m.ceil(num_estudiantes / 6)

    # Asegurarse de no exceder el máximo de 27 grupos
    num_grupos = min(min_grupos, 27)

    # Crear una lista con los identificadores de grupo
    grupos = [f'{i+1}' for i in range(num_grupos)]

    # Asignar grupos aleatoriamente a los estudiantes
    df['Grupo'] = np.random.choice(grupos, size=num_estudiantes, replace=True)

    # Ajustar el tamaño de los grupos para que no superen 6
    for grupo in grupos:
        estudiantes_en_grupo = df[df['Grupo'] == grupo]
        if len(estudiantes_en_grupo) > 6:
            # Seleccionar aleatoriamente estudiantes para mover a otros grupos
            estudiantes_a_mover = estudiantes_en_grupo.sample(n=len(estudiantes_en_grupo) - 6, replace=False)
            # Asignarles grupos aleatorios nuevamente
            df.loc[estudiantes_a_mover.index, 'Grupo'] = np.random.choice(grupos, size=len(estudiantes_a_mover), replace=True)

    return df

df_estudiantes = asignar_grupos_aleatorios(df_estudiantes)
df_estudiantes

,Nombres,Apellidos,Id,Email,Grupo
0,YESSICA,ACUÑA BARRANTES,1018485174,yessica-acuna@upc.edu.co,7
1,SIRLY HASLEIDY,AGUDELO QUINTERO,1014224233,sagudelo18@upc.edu.co,5
2,FERNANDO,AGUILAR GARCIA,17389648,fernando-aguilar@upc.edu.co,18
3,KIARA INES,ARCHBOLD ANGARITA,1018482816,kiara-archold@upc.edu.co,11
4,ANA MARIA,AREVALO AMAYA,1123086225,ana-arevalo3@upc.edu.co,5
...,...,...,...,...,...
153,EDDY PAULINE,VASQUEZ RODRIGUEZ,1022372740,eddy-vasquez@upc.edu.co,15
154,OSCAR LEONARDO,VEGA CASTRO,1075661411,oscar-vega2@upc.edu.co,26
155,FREDDY EDUARDO,VILLAFAÑE FUENTES,1046873078,freddy-villafane@upc.edu.co,19
156,NOHEMI,VILLARREAL NAVARRO,1022391981,nohemi-villarreal@upc.edu.co,18
157,KAREN JULIETH,ZABALA CASTAÑEDA,1032487033,karen-zabala@upc.edu.co,3

In [49]:
df_estudiantes[df_estudiantes['Grupo']=='7']

,Nombres,Apellidos,Id,Email,Grupo
0,YESSICA,ACUÑA BARRANTES,1018485174,yessica-acuna@upc.edu.co,7
31,CRISTIAN HERNAN,CHAVES FORERO,1016055232,cristian-chaves@upc.edu.co,7
80,LIDA YULIETH,MEDINA FRANCO,1022396315,lida-medina@upc.edu.co,7
99,LINA ROCIO,PENAGOS MORENO,1075655579,lina-penagos@upc.edu.co,7
107,WENDY VANESA,PULIDO REYES,1014282093,wendy-pulido@upc.edu.co,7
111,MARTHA LILIANA,RAMIREZ CARVAJAL,1075248408,martha-ramirez1@upc.edu.co,7
119,ALEJANDRO,RIOS SANCHEZ,1014281764,alejandro-rios1@upc.edu.co,7
123,CARLOS EDUARDO,RODRIGUEZ MORA,1010193363,carlos-rodriguez42@upc.edu.co,7

In [50]:
df_estudiantes['Grupo'].value_counts()

Grupo
7     8
4     8
5     7
22    7
3     7
25    7
16    7
24    6
15    6
18    6
20    6
23    6
1     6
26    6
10    6
19    6
17    6
12    6
27    5
2     5
8     5
13    5
6     5
21    4
11    4
14    4
9     4
Name: count, dtype: int64

In [51]:
# prompt: equilibra los grupos asignando personas de los grupos con 7 y 8 personas a grupos con menos de tal forma que no queden grupos con más de 6 estudiantes

import numpy as np
# Identificar grupos con más de 6 estudiantes
grupos_grandes = df_estudiantes['Grupo'].value_counts()
grupos_grandes = grupos_grandes[grupos_grandes > 6].index.tolist()

# Identificar grupos con menos de 6 estudiantes
grupos_pequenos = df_estudiantes['Grupo'].value_counts()
grupos_pequenos = grupos_pequenos[grupos_pequenos < 6].index.tolist()

# Iterar sobre los grupos grandes y mover estudiantes a grupos pequeños
for grupo_grande in grupos_grandes:
    estudiantes_en_grupo_grande = df_estudiantes[df_estudiantes['Grupo'] == grupo_grande]
    num_estudiantes_a_mover = len(estudiantes_en_grupo_grande) - 6

    # Mover estudiantes si hay grupos pequeños disponibles
    if len(grupos_pequenos) > 0:
        # Seleccionar aleatoriamente estudiantes para mover
        estudiantes_a_mover = estudiantes_en_grupo_grande.sample(n=num_estudiantes_a_mover, replace=False)

        # Asignarles grupos pequeños aleatoriamente
        grupos_destino = np.random.choice(grupos_pequenos, size=len(estudiantes_a_mover), replace=True)
        df_estudiantes.loc[estudiantes_a_mover.index, 'Grupo'] = grupos_destino

        # Actualizar la lista de grupos pequeños (puede que algunos se llenen)
        grupos_pequenos = df_estudiantes['Grupo'].value_counts()
        grupos_pequenos = grupos_pequenos[grupos_pequenos < 6].index.tolist()

# Verificar el tamaño de los grupos después del equilibrio
print("Tamaño de los grupos después del equilibrio:")
print(df_estudiantes['Grupo'].value_counts())

Tamaño de los grupos después del equilibrio:
Grupo
7     6
5     6
18    6
20    6
16    6
15    6
24    6
22    6
21    6
4     6
10    6
3     6
26    6
2     6
19    6
17    6
6     6
12    6
9     6
25    6
1     6
8     6
23    6
11    5
14    5
13    5
27    5
Name: count, dtype: int64

In [52]:
df_estudiantes

,Nombres,Apellidos,Id,Email,Grupo
0,YESSICA,ACUÑA BARRANTES,1018485174,yessica-acuna@upc.edu.co,7
1,SIRLY HASLEIDY,AGUDELO QUINTERO,1014224233,sagudelo18@upc.edu.co,5
2,FERNANDO,AGUILAR GARCIA,17389648,fernando-aguilar@upc.edu.co,18
3,KIARA INES,ARCHBOLD ANGARITA,1018482816,kiara-archold@upc.edu.co,11
4,ANA MARIA,AREVALO AMAYA,1123086225,ana-arevalo3@upc.edu.co,5
...,...,...,...,...,...
153,EDDY PAULINE,VASQUEZ RODRIGUEZ,1022372740,eddy-vasquez@upc.edu.co,15
154,OSCAR LEONARDO,VEGA CASTRO,1075661411,oscar-vega2@upc.edu.co,26
155,FREDDY EDUARDO,VILLAFAÑE FUENTES,1046873078,freddy-villafane@upc.edu.co,19
156,NOHEMI,VILLARREAL NAVARRO,1022391981,nohemi-villarreal@upc.edu.co,18
157,KAREN JULIETH,ZABALA CASTAÑEDA,1032487033,karen-zabala@upc.edu.co,3

No charts were generated by quickchart

In [54]:
# prompt: muestrame los grupos con personas que tengan compartan al menos un nombre

# Obtener los nombres de cada estudiante
nombres_estudiantes = df_estudiantes['Nombres'].tolist()

# Crear un conjunto para almacenar nombres ya vistos
nombres_vistos = set()

# Crear un diccionario para agrupar estudiantes por nombre compartido
grupos_nombres_compartidos = {}

# Iterar sobre cada estudiante y su nombre
for index, row in df_estudiantes.iterrows():
    nombre_completo = row['Nombres']
    grupo_estudiante = row['Grupo']

    # Dividir el nombre en nombres individuales
    nombres_individuales = nombre_completo.split()

    # Verificar si algún nombre individual ya fue visto en otro grupo
    nombres_compartidos_encontrados = set()
    for nombre in nombres_individuales:
        if nombre in nombres_vistos:
            nombres_compartidos_encontrados.add(nombre)
        else:
            nombres_vistos.add(nombre)

    # Si se encontraron nombres compartidos, agrupar al estudiante
    if nombres_compartidos_encontrados:
        for nombre_compartido in nombres_compartidos_encontrados:
            if nombre_compartido not in grupos_nombres_compartidos:
                grupos_nombres_compartidos[nombre_compartido] = set()
            grupos_nombres_compartidos[nombre_compartido].add(grupo_estudiante)

# Imprimir los grupos con personas que comparten al menos un nombre
print("Grupos con personas que comparten al menos un nombre:")
for nombre, grupos in grupos_nombres_compartidos.items():
    if len(grupos) > 1: # Solo mostrar si hay más de un grupo compartiendo el nombre
        print(f"Nombre compartido '{nombre}': Grupos {list(grupos)}")

# Opcional: Mostrar los estudiantes dentro de esos grupos
for nombre, grupos in grupos_nombres_compartidos.items():
     if len(grupos) > 1:
        print(f"\nEstudiantes con el nombre compartido '{nombre}':")
        for grupo in grupos:
            estudiantes_en_grupo = df_estudiantes[(df_estudiantes['Grupo'] == grupo) &
                                                  (df_estudiantes['Nombres'].str.contains(nombre, case=False))]
            print(f"  Grupo {grupo}:")
            for idx, estudiante_row in estudiantes_en_grupo.iterrows():
                 print(f"    - {estudiante_row['Nombres']}")

Grupos con personas que comparten al menos un nombre:
Nombre compartido 'MARIA': Grupos ['11', '26', '10', '3', '13', '15']
Nombre compartido 'ANA': Grupos ['3', '26']
Nombre compartido 'FERNANDO': Grupos ['20', '21', '15']
Nombre compartido 'CRISTIAN': Grupos ['7', '25', '21']
Nombre compartido 'CAROLINA': Grupos ['27', '17', '9', '21']
Nombre compartido 'ANDREA': Grupos ['17', '4', '1', '9', '3', '27', '21', '8']
Nombre compartido 'ERIKA': Grupos ['9', '12']
Nombre compartido 'TATIANA': Grupos ['9', '12']
Nombre compartido 'SERGIO': Grupos ['27', '3']
Nombre compartido 'LAURA': Grupos ['2', '19', '25', '13', '12']
Nombre compartido 'ALEXANDER': Grupos ['2', '26', '24', '16', '15']
Nombre compartido 'ALEJANDRA': Grupos ['14', '20', '10']
Nombre compartido 'DANIEL': Grupos ['23', '20', '25', '6']
Nombre compartido 'JOSE': Grupos ['22', '15']
Nombre compartido 'PAULA': Grupos ['9', '4']
Nombre compartido 'LUIS': Grupos ['14', '17']
Nombre compartido 'DIANA': Grupos ['27', '21']
Nombre compartido 'JUAN': Grupos ['10', '9', '6', '13', '16']
Nombre compartido 'OSCAR': Grupos ['25', '26']
Nombre compartido 'ANDRES': Grupos ['3', '13']
Nombre compartido 'FERNANDA': Grupos ['20', '16', '19']
Nombre compartido 'DAVID': Grupos ['27', '17', '23', '24']
Nombre compartido 'DIEGO': Grupos ['23', '1']
Nombre compartido 'CARLOS': Grupos ['9', '7', '13', '24']
Nombre compartido 'PAOLA': Grupos ['27', '17', '25', '12']
Nombre compartido 'JESSICA': Grupos ['17', '12']
Nombre compartido 'SEBASTIAN': Grupos ['9', '13']
Nombre compartido 'ALEJANDRO': Grupos ['23', '11']
Nombre compartido 'EDUARDO': Grupos ['7', '19']
Nombre compartido 'JAVIER': Grupos ['14', '2']
Nombre compartido 'KAREN': Grupos ['3', '13']

Estudiantes con el nombre compartido 'MARIA':
  Grupo 11:
    - MARIA DEL PILAR
  Grupo 26:
    - ANA MARIA
  Grupo 10:
    - MARIA DENIS
  Grupo 3:
    - ANA MARIA
  Grupo 13:
    - MARIA ANGELICA
  Grupo 15:
    - ERIKA MARIA

Estudiantes con el nombre compartido 'ANA':
  Grupo 3:
    - ANA MARIA
  Grupo 26:
    - ANA MARIA
    - LEIDY JOHANA

Estudiantes con el nombre compartido 'FERNANDO':
  Grupo 20:
    - DANIEL FERNANDO
  Grupo 21:
    - CRISTIAN FERNANDO
  Grupo 15:
    - ROBINSON FERNANDO

Estudiantes con el nombre compartido 'CRISTIAN':
  Grupo 7:
    - CRISTIAN HERNAN
  Grupo 25:
    - CRISTIAN CAMILO
  Grupo 21:
    - CRISTIAN FERNANDO

Estudiantes con el nombre compartido 'CAROLINA':
  Grupo 27:
    - DIANA CAROLINA
  Grupo 17:
    - LAURA CAROLINA
  Grupo 9:
    - LEIDY CAROLINA
  Grupo 21:
    - DEISY CAROLINA
    - DIANA CAROLINA

Estudiantes con el nombre compartido 'ANDREA':
  Grupo 17:
    - LUZ ANDREA
  Grupo 4:
    - PAULA ANDREA
  Grupo 1:
    - JENNY ANDREA
  Grupo 9:
    - PAULA ANDREA
  Grupo 3:
    - RUBI ANDREA
  Grupo 27:
    - PAOLA ANDREA
  Grupo 21:
    - ANDREA YULESSY
  Grupo 8:
    - KAREN ANDREA

Estudiantes con el nombre compartido 'ERIKA':
  Grupo 9:
    - ERIKA TATIANA
  Grupo 12:
    - ERIKA TATIANA

Estudiantes con el nombre compartido 'TATIANA':
  Grupo 9:
    - ERIKA TATIANA
  Grupo 12:
    - ERIKA TATIANA

Estudiantes con el nombre compartido 'SERGIO':
  Grupo 27:
    - SERGIO DAVID
  Grupo 3:
    - SERGIO ANDRES

Estudiantes con el nombre compartido 'LAURA':
  Grupo 2:
    - LAURA CAMILA
  Grupo 19:
    - LAURA FERNANDA
  Grupo 25:
    - LAURA
  Grupo 13:
    - LAURA NATALIA
  Grupo 12:
    - LAURA DAYANA

Estudiantes con el nombre compartido 'ALEXANDER':
  Grupo 2:
    - VICTOR ALEXANDER
  Grupo 26:
    - WILSON ALEXANDER
  Grupo 24:
    - DIEGO ALEXANDER
  Grupo 16:
    - JEISSON ALEXANDER
  Grupo 15:
    - JOSE ALEXANDER

Estudiantes con el nombre compartido 'ALEJANDRA':
  Grupo 14:
    - LIZETH ALEJANDRA
  Grupo 20:
    - MAYRA ALEJANDRA
  Grupo 10:
    - NORA ALEJANDRA

Estudiantes con el nombre compartido 'DANIEL':
  Grupo 23:
    - DANIEL ARTURO
  Grupo 20:
    - DANIEL FERNANDO
  Grupo 25:
    - OSCAR DANIEL
  Grupo 6:
    - DANIELA DE JESUS
    - KEVIN DANIEL

Estudiantes con el nombre compartido 'JOSE':
  Grupo 22:
    - EDUARDO JOSE
  Grupo 15:
    - JOSE ALEXANDER

Estudiantes con el nombre compartido 'PAULA':
  Grupo 9:
    - PAULA ANDREA
  Grupo 4:
    - PAULA ANDREA

Estudiantes con el nombre compartido 'LUIS':
  Grupo 14:
    - LUIS OMAR
  Grupo 17:
    - LUIS YEISSON

Estudiantes con el nombre compartido 'DIANA':
  Grupo 27:
    - DIANA CAROLINA
  Grupo 21:
    - DIANA CAROLINA

Estudiantes con el nombre compartido 'JUAN':
  Grupo 10:
    - JUAN FELIPE
  Grupo 9:
    - JUAN SEBASTIAN
  Grupo 6:
    - JUAN CARLOS
  Grupo 13:
    - JUAN SEBASTIAN
  Grupo 16:
    - JUAN SEBASTIAN

Estudiantes con el nombre compartido 'OSCAR':
  Grupo 25:
    - OSCAR ARMANDO
    - OSCAR DANIEL
  Grupo 26:
    - OSCAR LEONARDO

Estudiantes con el nombre compartido 'ANDRES':
  Grupo 3:
    - NICOLAS ANDRES
    - SERGIO ANDRES
  Grupo 13:
    - CARLOS ANDRES

Estudiantes con el nombre compartido 'FERNANDA':
  Grupo 20:
    - LUISA FERNANDA
  Grupo 16:
    - LUISA FERNANDA
  Grupo 19:
    - LAURA FERNANDA
    - YESSYCA FERNANDA

Estudiantes con el nombre compartido 'DAVID':
  Grupo 27:
    - SERGIO DAVID
    - DAVID MAURICIO
  Grupo 17:
    - DAVID ALFONSO
  Grupo 23:
    - JULIAN DAVID
  Grupo 24:
    - DAVID SANTIAGO

Estudiantes con el nombre compartido 'DIEGO':
  Grupo 23:
    - DIEGO ALEJANDRO
  Grupo 1:
    - DIEGO ALEJANDRO

Estudiantes con el nombre compartido 'CARLOS':
  Grupo 9:
    - CARLOS AUGUSTO
  Grupo 7:
    - CARLOS EDUARDO
  Grupo 13:
    - CARLOS ANDRES
  Grupo 24:
    - CARLOS IVAN

Estudiantes con el nombre compartido 'PAOLA':
  Grupo 27:
    - NESLY PAOLA
    - PAOLA ANDREA
  Grupo 17:
    - JESSICA PAOLA
  Grupo 25:
    - DIANIS PAOLA
  Grupo 12:
    - JESSICA PAOLA

Estudiantes con el nombre compartido 'JESSICA':
  Grupo 17:
    - JESSICA PAOLA
  Grupo 12:
    - JESSICA PAOLA

Estudiantes con el nombre compartido 'SEBASTIAN':
  Grupo 9:
    - JUAN SEBASTIAN
  Grupo 13:
    - JUAN SEBASTIAN

Estudiantes con el nombre compartido 'ALEJANDRO':
  Grupo 23:
    - DIEGO ALEJANDRO
  Grupo 11:
    - ALEJANDRO

Estudiantes con el nombre compartido 'EDUARDO':
  Grupo 7:
    - CARLOS EDUARDO
  Grupo 19:
    - FREDDY EDUARDO

Estudiantes con el nombre compartido 'JAVIER':
  Grupo 14:
    - LEONARDO JAVIER
  Grupo 2:
    - NELSON JAVIER

Estudiantes con el nombre compartido 'KAREN':
  Grupo 3:
    - KAREN JULIETH
  Grupo 13:
    - KAREN DANIELA